packages:
  - "apps/*"
  - "packages/*"

minimumReleaseAge: 0
strictDepBuilds: false

allowBuilds:
  "@nestjs/core": true
  "@prisma/client": true
  "@prisma/engines": true
  "prisma": true
  "keccak": true
  "secp256k1": true
