// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { FractionalPropertyToken$Type } from "./FractionalPropertyToken";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["FractionalPropertyToken"]: FractionalPropertyToken$Type;
    ["contracts/FractionalPropertyToken.sol:FractionalPropertyToken"]: FractionalPropertyToken$Type;
  }

  interface ContractTypesMap {
    ["FractionalPropertyToken"]: GetContractReturnType<FractionalPropertyToken$Type["abi"]>;
    ["contracts/FractionalPropertyToken.sol:FractionalPropertyToken"]: GetContractReturnType<FractionalPropertyToken$Type["abi"]>;
  }
}
